/**
 * Script Generator Utility
 * 
 * Generates shell scripts from wizard stage commands.
 * Supports single stage and full installation script generation.
 */

import { StageInfo, Platform, LinuxDistro } from '@/lib/types/wizard';
import { STAGES, getFilteredCommands } from '@/lib/data/wizard-stages';

export interface ScriptOptions {
  /** Target platform */
  platform: Platform;
  /** Linux distribution (if platform is linux) */
  distro?: LinuxDistro | null;
  /** Include comments in script */
  includeComments?: boolean;
  /** Include error handling (set -e) */
  includeErrorHandling?: boolean;
  /** Include stage headers */
  includeHeaders?: boolean;
}

const DEFAULT_OPTIONS: ScriptOptions = {
  platform: 'linux',
  distro: null,
  includeComments: true,
  includeErrorHandling: true,
  includeHeaders: true,
};

/**
 * Generate a shell script header
 */
function generateHeader(
  title: string,
  platform: Platform,
  distro?: LinuxDistro | null,
  includeErrorHandling: boolean = true
): string {
  const lines: string[] = [
    '#!/bin/bash',
    '#',
    `# ${title}`,
    `# Generated by Sam's LFS Installation Wizard`,
    `# Date: ${new Date().toISOString()}`,
    `# Platform: ${platform}`,
  ];

  if (distro) {
    lines.push(`# Distribution: ${distro}`);
  }

  lines.push('#');
  lines.push('');

  if (includeErrorHandling) {
    lines.push('# Exit on error');
    lines.push('set -e');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate script content for a single stage
 */
export function generateStageScript(
  stage: StageInfo,
  options: Partial<ScriptOptions> = {}
): string {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const commands = getFilteredCommands(stage, opts.platform, opts.distro);
  
  const lines: string[] = [];

  // Add header
  if (opts.includeHeaders) {
    lines.push(generateHeader(
      `LFS Stage ${stage.id}: ${stage.title}`,
      opts.platform,
      opts.distro,
      opts.includeErrorHandling
    ));
  }

  // Add stage description
  if (opts.includeComments) {
    lines.push(`# Stage ${stage.id}: ${stage.title}`);
    lines.push(`# ${stage.description}`);
    lines.push(`# Estimated time: ${stage.estimatedTime}`);
    if (stage.diskSpace !== '0') {
      lines.push(`# Disk space required: ${stage.diskSpace}`);
    }
    lines.push('');
  }

  // Add commands
  for (const cmd of commands) {
    // Skip pure comment commands (they're informational)
    if (cmd.command.trim().startsWith('#') && !cmd.command.includes('\n')) {
      if (opts.includeComments) {
        lines.push(cmd.command);
      }
      continue;
    }

    // Add command description as comment
    if (opts.includeComments && cmd.description) {
      lines.push(`# ${cmd.description}`);
    }

    // Add warning if present
    if (opts.includeComments && cmd.warningMessage) {
      lines.push(`# WARNING: ${cmd.warningMessage}`);
    }

    // Add the command
    lines.push(cmd.command);
    lines.push('');
  }

  // Add completion message
  lines.push(`echo "Stage ${stage.id} (${stage.title}) complete!"`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate a full installation script for all stages
 */
export function generateFullScript(
  options: Partial<ScriptOptions> = {}
): string {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  
  const lines: string[] = [];

  // Add main header
  lines.push(generateHeader(
    'LFS Full Installation Script',
    opts.platform,
    opts.distro,
    opts.includeErrorHandling
  ));

  // Add overview
  if (opts.includeComments) {
    lines.push('# ============================================================================');
    lines.push('# LFS 12.0 Full Installation Script');
    lines.push('# ============================================================================');
    lines.push('#');
    lines.push('# This script contains all commands for building Linux From Scratch.');
    lines.push('# It is recommended to run each stage manually and verify before proceeding.');
    lines.push('#');
    lines.push('# Stages:');
    for (const stage of STAGES) {
      lines.push(`#   ${stage.id}. ${stage.title} (${stage.estimatedTime})`);
    }
    lines.push('#');
    lines.push('# ============================================================================');
    lines.push('');
  }

  // Add each stage
  for (const stage of STAGES) {
    const commands = getFilteredCommands(stage, opts.platform, opts.distro);
    
    // Skip stages with no commands for this platform
    if (commands.length === 0) {
      continue;
    }

    // Stage header
    lines.push('');
    lines.push('# ============================================================================');
    lines.push(`# Stage ${stage.id}: ${stage.title}`);
    lines.push('# ============================================================================');
    lines.push('');

    if (opts.includeComments) {
      lines.push(`# ${stage.description}`);
      lines.push(`# Estimated time: ${stage.estimatedTime}`);
      if (stage.diskSpace !== '0') {
        lines.push(`# Disk space: ${stage.diskSpace}`);
      }
      lines.push('');
    }

    // Add commands
    for (const cmd of commands) {
      if (cmd.command.trim().startsWith('#') && !cmd.command.includes('\n')) {
        if (opts.includeComments) {
          lines.push(cmd.command);
        }
        continue;
      }

      if (opts.includeComments && cmd.description) {
        lines.push(`# ${cmd.description}`);
      }

      if (opts.includeComments && cmd.warningMessage) {
        lines.push(`# WARNING: ${cmd.warningMessage}`);
      }

      lines.push(cmd.command);
      lines.push('');
    }

    lines.push(`echo "Stage ${stage.id} complete!"`);
    lines.push('');
  }

  // Final message
  lines.push('');
  lines.push('echo "============================================"');
  lines.push('echo "LFS Installation Complete!"');
  lines.push('echo "============================================"');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate script for a range of stages
 */
export function generateStageRangeScript(
  startStage: number,
  endStage: number,
  options: Partial<ScriptOptions> = {}
): string {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const stages = STAGES.filter(s => s.id >= startStage && s.id <= endStage);
  
  const lines: string[] = [];

  // Add header
  lines.push(generateHeader(
    `LFS Stages ${startStage}-${endStage}`,
    opts.platform,
    opts.distro,
    opts.includeErrorHandling
  ));

  // Add each stage
  for (const stage of stages) {
    const commands = getFilteredCommands(stage, opts.platform, opts.distro);
    
    if (commands.length === 0) continue;

    lines.push('');
    lines.push(`# === Stage ${stage.id}: ${stage.title} ===`);
    lines.push('');

    for (const cmd of commands) {
      if (cmd.command.trim().startsWith('#') && !cmd.command.includes('\n')) {
        if (opts.includeComments) {
          lines.push(cmd.command);
        }
        continue;
      }

      if (opts.includeComments && cmd.description) {
        lines.push(`# ${cmd.description}`);
      }

      lines.push(cmd.command);
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Get the filename for a script download
 */
export function getScriptFilename(
  stageId?: number,
  platform?: Platform
): string {
  const platformSuffix = platform ? `-${platform}` : '';
  
  if (stageId) {
    return `lfs-stage-${stageId}${platformSuffix}.sh`;
  }
  
  return `lfs-full-install${platformSuffix}.sh`;
}

/**
 * Create a downloadable blob from script content
 */
export function createScriptBlob(content: string): Blob {
  return new Blob([content], { type: 'text/plain;charset=utf-8' });
}

/**
 * Trigger a script download in the browser
 */
export function downloadScript(
  content: string,
  filename: string
): void {
  const blob = createScriptBlob(content);
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  
  document.body.appendChild(a);
  a.click();
  
  // Cleanup
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Count the number of executable commands in a stage
 */
export function countExecutableCommands(
  stage: StageInfo,
  platform: Platform,
  distro?: LinuxDistro | null
): number {
  const commands = getFilteredCommands(stage, platform, distro);
  return commands.filter(cmd => !cmd.command.trim().startsWith('#')).length;
}

/**
 * Get total executable commands across all stages
 */
export function getTotalExecutableCommands(
  platform: Platform,
  distro?: LinuxDistro | null
): number {
  return STAGES.reduce((total, stage) => {
    return total + countExecutableCommands(stage, platform, distro);
  }, 0);
}
