#!/bin/bash
# Ultra-minimal LFS build entry point for debugging
echo "====================================="
echo "LFS Builder Starting"
echo "====================================="
echo "Date: $(date)"
echo "Hostname: $(hostname)"
echo "User: $(whoami)"
echo "PWD: $(pwd)"
echo ""
echo "Environment variables:"
env | grep -E "(LFS|BUILD|PROJECT|GCS)" | sort
echo ""
echo "Directory /app:"
ls -lah /app || echo "Failed to list /app"
echo ""
echo "Directory /app/helpers:"
ls -lah /app/helpers || echo "Failed to list /app/helpers"
echo ""
echo "Checking Node.js:"
node --version || echo "Node not found"
npm --version || echo "npm not found"
echo ""
echo "Checking helper package:"
cd /app/helpers && npm list || echo "Failed to check helpers packages"
echo ""
echo "====================================="
echo "Setup complete. Would start build here."
echo "====================================="
exit 0
